### Getting all users
GET http://localhost:4000/api/users/

### Get user by ID
GET http://localhost:4000/api/users/1

### Creating a new user
POST http://localhost:4000/api/users/new
content-type: application/json

{
    "name": "Test",
    "email": "Test@hotmail.com"
}

### Deleting a user
DELETE http://localhost:4000/api/users/5

### Updating a user
PUT http://localhost:4000/api/users/5
Content-Type: application/json

{
    "name": "Updated",
    "email": "Updated@hotmail.com"
}